"""Tests for checkowners.generate module."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

from checkowners.generate import (
    _build_codeowners_content,
    _collect_owned_paths,
    _collect_unowned_paths,
    _normalize_path,
    generate_codeowners,
)
from checkowners.models import (
    AnalysisConfig,
    Config,
    GithubConfig,
    OutputConfig,
    OwnerEntry,
    OwnershipMap,
    PathOwnership,
)

_NOW = datetime(2026, 5, 28, 12, 0, 0, tzinfo=UTC)


def _entry(handle: str, confidence: float, commits: int = 5) -> OwnerEntry:
    return OwnerEntry(
        handle=handle,
        confidence=confidence,
        last_commit=_NOW,
        commits=commits,
    )


def _make_ownership(
    raw: dict[str, tuple[OwnerEntry, ...]],
) -> OwnershipMap:
    paths = {p: PathOwnership(owners=owners, bus_factor=len(owners)) for p, owners in raw.items()}
    return OwnershipMap(paths=paths, last_analyzed=_NOW)


def _zero_threshold() -> Config:
    return Config(analysis=AnalysisConfig(confidence_threshold=0.0))


def test_generate_writes_file(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = generate_codeowners(tmp_path, ownership, config)
    codeowners = tmp_path / ".github" / "CODEOWNERS"
    assert codeowners.exists()
    assert codeowners.read_text(encoding="utf-8") == content


def test_generate_includes_header() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.\n")


def test_generate_custom_header() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(header="# Custom header"),
    )
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Custom header\n")


def test_generate_paths_sorted() -> None:
    ownership = _make_ownership(
        {
            "z.py": (_entry("alice@example.com", 0.9),),
            "a.py": (_entry("bob@example.com", 0.9),),
            "m.py": (_entry("carol@example.com", 0.9),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines[0].startswith("/a.py")
    assert lines[1].startswith("/m.py")
    assert lines[2].startswith("/z.py")


def test_generate_owners_confidence_ordered() -> None:
    ownership = _make_ownership(
        {"src/api.py": (_entry("alice@example.com", 0.95), _entry("bob@example.com", 0.6))}
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/src/api.py alice@example.com bob@example.com" in content


def test_generate_confidence_threshold_filters_owners() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("alice@example.com", 0.4), _entry("bob@example.com", 0.1))}
    )
    config = Config(analysis=AnalysisConfig(confidence_threshold=0.3))
    content = _build_codeowners_content(ownership, config)
    assert "alice@example.com" in content
    assert "bob@example.com" not in content


def test_generate_confidence_threshold_drops_path_when_all_owners_filtered() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("alice@example.com", 0.1),)}
    )
    config = Config(analysis=AnalysisConfig(confidence_threshold=0.3))
    content = _build_codeowners_content(ownership, config)
    assert "src/main.py" not in content


def test_generate_include_confidence_annotates() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("alice@example.com", 0.92), _entry("bob@example.com", 0.71))}
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(include_confidence=True),
    )
    content = _build_codeowners_content(ownership, config)
    assert "/src/main.py alice@example.com bob@example.com  # alice@example.com(0.92) bob@example.com(0.71)" in content
    assert "Confidence scores reflect each owner's expertise" in content


def test_generate_include_confidence_disabled_no_annotation() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("alice@example.com", 0.92),)}
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(include_confidence=False),
    )
    content = _build_codeowners_content(ownership, config)
    assert "0.92" not in content


def test_generate_include_unowned_true() -> None:
    ownership = OwnershipMap(
        paths={
            "src/main.py": PathOwnership(
                owners=(_entry("alice@example.com", 0.9),), bus_factor=1
            ),
            "src/orphan.py": PathOwnership(owners=(), bus_factor=0),
        },
        last_analyzed=_NOW,
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(include_unowned=True),
    )
    content = _build_codeowners_content(ownership, config)
    assert "# Unowned paths (needs triage)" in content
    assert "# /src/orphan.py" in content


def test_generate_include_unowned_false() -> None:
    ownership = OwnershipMap(
        paths={
            "src/main.py": PathOwnership(
                owners=(_entry("alice@example.com", 0.9),), bus_factor=1
            ),
            "src/orphan.py": PathOwnership(owners=(), bus_factor=0),
        },
        last_analyzed=_NOW,
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(include_unowned=False),
    )
    content = _build_codeowners_content(ownership, config)
    assert "orphan" not in content


def test_generate_empty_ownership(tmp_path: Path) -> None:
    ownership = _make_ownership({})
    config = _zero_threshold()
    content = generate_codeowners(tmp_path, ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.\n")
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == []


def test_generate_creates_github_dir(tmp_path: Path) -> None:
    ownership = _make_ownership({"f.py": (_entry("alice@example.com", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold())
    assert (tmp_path / ".github").is_dir()
    assert (tmp_path / ".github" / "CODEOWNERS").is_file()


def test_normalize_path_adds_leading_slash() -> None:
    assert _normalize_path("src/main.py") == "/src/main.py"
    assert _normalize_path("/src/main.py") == "/src/main.py"


def test_collect_owned_paths_sorted() -> None:
    ownership = _make_ownership(
        {
            "b.py": (_entry("alice@example.com", 0.9),),
            "a.py": (_entry("bob@example.com", 0.9),),
        }
    )
    result = _collect_owned_paths(ownership, 0.0)
    assert result[0][0] == "/a.py"
    assert result[1][0] == "/b.py"


def test_collect_unowned_paths_sorted() -> None:
    ownership = OwnershipMap(
        paths={
            "z.py": PathOwnership(owners=(), bus_factor=0),
            "a.py": PathOwnership(owners=(), bus_factor=0),
            "m.py": PathOwnership(owners=(_entry("alice@example.com", 0.9),), bus_factor=1),
        },
        last_analyzed=_NOW,
    )
    result = _collect_unowned_paths(ownership)
    assert result == ["/a.py", "/z.py"]


def test_generate_overwrites_existing(tmp_path: Path) -> None:
    github_dir = tmp_path / ".github"
    github_dir.mkdir()
    (github_dir / "CODEOWNERS").write_text("old content", encoding="utf-8")
    ownership = _make_ownership({"f.py": (_entry("alice@example.com", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold())
    content = (github_dir / "CODEOWNERS").read_text(encoding="utf-8")
    assert "old content" not in content
    assert content.startswith("# Generated by checkOwners.")


def test_generate_trailing_newline() -> None:
    ownership = _make_ownership({"f.py": (_entry("alice@example.com", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert content.endswith("\n")


def test_generate_with_team_resolution() -> None:
    ownership = _make_ownership(
        {
            "src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8)),
            "src/util.py": (_entry("@carol", 0.9),),
        }
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(org="myorg", resolve_teams=True),
    )

    def mock_resolver(owners: tuple[str, ...]) -> str | None:
        if set(owners) == {"@alice", "@bob"}:
            return "@myorg/backend"
        return None

    with patch("checkowners.github.create_team_resolver", return_value=mock_resolver):
        content = _build_codeowners_content(ownership, config, token="ghp_test", org="myorg")
    assert "/src/main.py @myorg/backend" in content
    assert "/src/util.py @carol" in content


def test_generate_team_resolution_disabled() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))}
    )
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(resolve_teams=False),
    )
    content = _build_codeowners_content(ownership, config, token="ghp_test", org="myorg")
    assert "@alice @bob" in content


def test_generate_with_codeowners_path(tmp_path: Path) -> None:
    ownership = _make_ownership({"f.py": (_entry("alice@example.com", 0.9),)})
    target = tmp_path / "CODEOWNERS"
    generate_codeowners(tmp_path, ownership, _zero_threshold(), codeowners_path=target)
    assert target.exists()
    assert target.read_text(encoding="utf-8").startswith("# Generated by checkOwners.")
