"""Tests for checkowners.generate module."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

from checkowners.generate import (
    _build_codeowners_content,
    _collect_owned_paths,
    _collect_unowned_paths,
    _normalize_path,
    generate_codeowners,
)
from checkowners.models import Config, GithubConfig, OutputConfig, OwnershipMap

_NOW = datetime.now(UTC)


def _make_ownership(owners: dict[str, tuple[str, ...]]) -> OwnershipMap:
    return OwnershipMap(owners=owners, last_analyzed=_NOW)


def test_generate_writes_file(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": ("alice@example.com",)})
    config = Config()
    content = generate_codeowners(tmp_path, ownership, config)
    codeowners = tmp_path / ".github" / "CODEOWNERS"
    assert codeowners.exists()
    assert codeowners.read_text(encoding="utf-8") == content


def test_generate_includes_header() -> None:
    ownership = _make_ownership({"src/main.py": ("alice@example.com",)})
    config = Config()
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.\n")


def test_generate_custom_header() -> None:
    ownership = _make_ownership({"src/main.py": ("alice@example.com",)})
    config = Config(output=OutputConfig(header="# Custom header"))
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Custom header\n")


def test_generate_paths_sorted() -> None:
    ownership = _make_ownership(
        {
            "z.py": ("alice@example.com",),
            "a.py": ("bob@example.com",),
            "m.py": ("carol@example.com",),
        }
    )
    config = Config()
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines[0].startswith("/a.py")
    assert lines[1].startswith("/m.py")
    assert lines[2].startswith("/z.py")


def test_generate_multiple_owners() -> None:
    ownership = _make_ownership(
        {
            "src/api.py": ("alice@example.com", "bob@example.com"),
        }
    )
    config = Config()
    content = _build_codeowners_content(ownership, config)
    assert "/src/api.py alice@example.com bob@example.com" in content


def test_generate_include_unowned_true() -> None:
    ownership = _make_ownership(
        {
            "src/main.py": ("alice@example.com",),
            "src/orphan.py": (),
        }
    )
    config = Config(output=OutputConfig(include_unowned=True))
    content = _build_codeowners_content(ownership, config)
    assert "# Unowned paths (needs triage)" in content
    assert "# /src/orphan.py" in content


def test_generate_include_unowned_false() -> None:
    ownership = _make_ownership(
        {
            "src/main.py": ("alice@example.com",),
            "src/orphan.py": (),
        }
    )
    config = Config(output=OutputConfig(include_unowned=False))
    content = _build_codeowners_content(ownership, config)
    assert "orphan" not in content


def test_generate_empty_ownership(tmp_path: Path) -> None:
    ownership = _make_ownership({})
    config = Config()
    content = generate_codeowners(tmp_path, ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.\n")
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == []


def test_generate_creates_github_dir(tmp_path: Path) -> None:
    ownership = _make_ownership({"f.py": ("alice@example.com",)})
    config = Config()
    generate_codeowners(tmp_path, ownership, config)
    assert (tmp_path / ".github").is_dir()
    assert (tmp_path / ".github" / "CODEOWNERS").is_file()


def test_normalize_path_adds_leading_slash() -> None:
    assert _normalize_path("src/main.py") == "/src/main.py"
    assert _normalize_path("/src/main.py") == "/src/main.py"


def test_collect_owned_paths_sorted() -> None:
    ownership = _make_ownership(
        {
            "b.py": ("alice@example.com",),
            "a.py": ("bob@example.com",),
        }
    )
    result = _collect_owned_paths(ownership)
    assert result[0][0] == "/a.py"
    assert result[1][0] == "/b.py"


def test_collect_unowned_paths_sorted() -> None:
    ownership = _make_ownership(
        {
            "z.py": (),
            "a.py": (),
            "m.py": ("alice@example.com",),
        }
    )
    result = _collect_unowned_paths(ownership)
    assert result == ["/a.py", "/z.py"]


def test_generate_overwrites_existing(tmp_path: Path) -> None:
    github_dir = tmp_path / ".github"
    github_dir.mkdir()
    (github_dir / "CODEOWNERS").write_text("old content", encoding="utf-8")
    ownership = _make_ownership({"f.py": ("alice@example.com",)})
    config = Config()
    generate_codeowners(tmp_path, ownership, config)
    content = (github_dir / "CODEOWNERS").read_text(encoding="utf-8")
    assert "old content" not in content
    assert content.startswith("# Generated by checkOwners.")


def test_generate_trailing_newline() -> None:
    ownership = _make_ownership({"f.py": ("alice@example.com",)})
    config = Config()
    content = _build_codeowners_content(ownership, config)
    assert content.endswith("\n")


def test_generate_with_team_resolution() -> None:
    ownership = _make_ownership({
        "src/main.py": ("@alice", "@bob"),
        "src/util.py": ("@carol",),
    })
    config = Config(github=GithubConfig(org="myorg", resolve_teams=True))

    def mock_resolver(owners: tuple[str, ...]) -> str | None:
        if set(owners) == {"@alice", "@bob"}:
            return "@myorg/backend"
        return None

    with patch("checkowners.github.create_team_resolver", return_value=mock_resolver):
        content = _build_codeowners_content(ownership, config, token="ghp_test", org="myorg")
    assert "/src/main.py @myorg/backend" in content
    assert "/src/util.py @carol" in content


def test_generate_team_resolution_disabled() -> None:
    ownership = _make_ownership({"src/main.py": ("@alice", "@bob")})
    config = Config(github=GithubConfig(resolve_teams=False))
    content = _build_codeowners_content(ownership, config, token="ghp_test", org="myorg")
    assert "@alice @bob" in content


def test_generate_with_codeowners_path(tmp_path: Path) -> None:
    ownership = _make_ownership({"f.py": ("alice@example.com",)})
    config = Config()
    target = tmp_path / "CODEOWNERS"
    generate_codeowners(tmp_path, ownership, config, codeowners_path=target)
    assert target.exists()
    assert target.read_text(encoding="utf-8").startswith("# Generated by checkOwners.")
