"""Tests for checkowners.config module."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from checkowners.config import find_codeowners_path, load_config
from checkowners.models import Config


def _write_config(tmp_path: Path, content: str) -> Path:
    config_dir = tmp_path / ".github"
    config_dir.mkdir()
    (config_dir / "checkowners.yml").write_text(content, encoding="utf-8")
    return tmp_path


def test_load_config_defaults(tmp_path: Path) -> None:
    cfg = load_config(repo_root=tmp_path)
    assert cfg == Config()
    assert cfg.analysis.lookback_days == 180
    assert cfg.analysis.min_commits == 3
    assert cfg.analysis.top_n_owners == 2
    assert cfg.paths.exclude == ("*.lock", "dist/**", "vendor/**")
    assert cfg.output.header == "# Generated by checkOwners. Do not edit manually."
    assert cfg.output.include_unowned is False
    assert cfg.drift.mode == "commit"
    assert cfg.drift.compare_to == "auto"
    assert cfg.notifications.webhook_url == ""
    assert cfg.notifications.include_unchanged is False


def test_load_config_empty_file(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "")
    cfg = load_config(repo_root=root)
    assert cfg == Config()


def test_load_config_partial_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "analysis:\n  lookback_days: 365\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 365
    assert cfg.analysis.min_commits == 3
    assert cfg.analysis.top_n_owners == 2
    assert cfg.paths == Config().paths
    assert cfg.output == Config().output


def test_load_config_full_override(tmp_path: Path) -> None:
    content = """\
analysis:
  lookback_days: 90
  min_commits: 5
  top_n_owners: 3
paths:
  exclude:
    - "*.tmp"
    - "build/**"
output:
  header: "# Custom header"
  include_unowned: true
drift:
  mode: repo
  compare_to: main
notifications:
  webhook_url: "https://hooks.example.com/drift"
  include_unchanged: true
"""
    root = _write_config(tmp_path, content)
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 90
    assert cfg.analysis.min_commits == 5
    assert cfg.analysis.top_n_owners == 3
    assert cfg.paths.exclude == ("*.tmp", "build/**")
    assert cfg.output.header == "# Custom header"
    assert cfg.output.include_unowned is True
    assert cfg.drift.mode == "repo"
    assert cfg.drift.compare_to == "main"
    assert cfg.notifications.webhook_url == "https://hooks.example.com/drift"
    assert cfg.notifications.include_unchanged is True


def test_load_config_invalid_yaml(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "[[[invalid yaml")
    with pytest.raises(yaml.YAMLError):
        load_config(repo_root=root)


def test_load_config_non_mapping(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "- a\n- b\n")
    with pytest.raises(ValueError, match="expected a YAML mapping"):
        load_config(repo_root=root)


def test_load_config_unknown_keys_ignored(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "custom_field: true\nanother: 42\n")
    cfg = load_config(repo_root=root)
    assert cfg == Config()


def test_load_config_custom_repo_root(tmp_path: Path) -> None:
    sub = tmp_path / "myrepo"
    sub.mkdir()
    root = _write_config(sub, "analysis:\n  min_commits: 10\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.min_commits == 10


def test_drift_mode_literal(tmp_path: Path) -> None:
    for mode in ("commit", "repo", "both"):
        root = _write_config(tmp_path, f"drift:\n  mode: {mode}\n")
        cfg = load_config(repo_root=root)
        assert cfg.drift.mode == mode
        # Clean up for next iteration
        (tmp_path / ".github" / "checkowners.yml").unlink()
        (tmp_path / ".github").rmdir()


def test_paths_exclude_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "paths:\n  exclude:\n    - '*.tmp'\n")
    cfg = load_config(repo_root=root)
    assert cfg.paths.exclude == ("*.tmp",)
    assert "*.lock" not in cfg.paths.exclude


def test_load_config_github_section(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "github:\n  org: myorg\n  resolve_teams: false\n")
    cfg = load_config(repo_root=root)
    assert cfg.github.org == "myorg"
    assert cfg.github.resolve_teams is False
    assert cfg.github.resolve_handles is True


def test_find_codeowners_path_github_dir(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_root(tmp_path: Path) -> None:
    (tmp_path / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "CODEOWNERS"


def test_find_codeowners_path_docs(tmp_path: Path) -> None:
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "docs" / "CODEOWNERS"


def test_find_codeowners_path_priority(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# github", encoding="utf-8")
    (tmp_path / "CODEOWNERS").write_text("# root", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_none_exist(tmp_path: Path) -> None:
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"
