"""Data models for checkOwners. Only dataclasses; no other classes."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


@dataclass(frozen=True)
class AnalysisConfig:
    lookback_days: int = 180
    min_commits: int = 3
    top_n_owners: int = 2


@dataclass(frozen=True)
class PathsConfig:
    exclude: tuple[str, ...] = ("*.lock", "dist/**", "vendor/**")


@dataclass(frozen=True)
class OutputConfig:
    header: str = "# Generated by checkOwners. Do not edit manually."
    include_unowned: bool = False


@dataclass(frozen=True)
class DriftConfig:
    mode: Literal["commit", "repo", "both"] = "commit"
    compare_to: str = "auto"


@dataclass(frozen=True)
class NotificationsConfig:
    webhook_url: str = ""
    include_unchanged: bool = False


@dataclass(frozen=True)
class GithubConfig:
    org: str = ""
    resolve_handles: bool = True
    resolve_teams: bool = True


@dataclass(frozen=True)
class Config:
    analysis: AnalysisConfig = field(default_factory=AnalysisConfig)
    paths: PathsConfig = field(default_factory=PathsConfig)
    output: OutputConfig = field(default_factory=OutputConfig)
    drift: DriftConfig = field(default_factory=DriftConfig)
    notifications: NotificationsConfig = field(default_factory=NotificationsConfig)
    github: GithubConfig = field(default_factory=GithubConfig)


@dataclass(frozen=True)
class OwnershipMap:
    owners: dict[str, tuple[str, ...]]
    last_analyzed: datetime


@dataclass(frozen=True)
class DriftResult:
    stale: tuple[str, ...]
    missing: tuple[str, ...]
    changed: tuple[str, ...]
    drift_detected: bool
